---
spring:
  application:
    name: hmall-page
  servlet:
    multipart:
      max-file-size: 50MB

server:
  port: 9021
debug: false
logging:
  level:
    root: info

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:9001/eureka/

